# Generated by Django 4.2.13 on 2024-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_quantity_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, verbose_name='URL'),
        ),
    ]
