# Generated by Django 4.2.13 on 2024-07-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product']},
        ),
    ]
